VAGRANTFILE_API_VERSION = "2"

#
# L'installazione prevede: 
# - Oracle Java SDK 8 
# - DB2 Express-C
# - Apache Tomee
#

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	# Ubuntu trusty 64 VirtualBox.
	config.vm.box = "ubuntu/trusty64"

	# cartella per le risorse condivise 
	config.vm.synced_folder "./shared/", "/home/vagrant/shared", :mount_options => ["dmode=777", "fmode=777"]

	config.vm.hostname = "server"    
	config.vm.network :forwarded_port, guest: 8080, host: 8090

        config.vm.provider "virtualbox" do |v| 
            v.memory = 1024 
        end 

        config.vm.network "forwarded_port", guest: 22, host: 2211, id: 'ssh', auto_correct: true
        config.ssh.forward_agent = true
 
        # provisioning con bash 
        config.vm.provision :shell, :inline => 'apt-get update'
        config.vm.provision :shell, path: "./shared/scripts/setup-java.sh"
	config.vm.provision :shell, path: "./shared/scripts/setup-db2.sh"
	config.vm.provision :shell, path: "./shared/scripts/setup-apache-tomee.sh"
	#script da eseguire ad ogni avvio della macchina
        config.vm.provision :shell, path: "./shared/scripts/startup-apache.sh", run:"always"

        config.vm.provision :shell, 
            inline: "echo  'configurazione vm server completata'"

end
