# 
# Vagrantfile per i progetti client-server
# - un nodo server 
# - un nodo client 
# 

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Configurazioni comuni.

    # Ubuntu trusty 64 VirtualBox.
    config.vm.box = "ubuntu/trusty64"

    # folder per le risorse condivise 
    config.vm.synced_folder "./shared/", "/home/vagrant/shared", :mount_options => ["dmode=777", "fmode=777"]

    #
    # Configurazione del nodo "server", che prevede: 
    # - Oracle Java SDK 8 
    # - DB2 Express-C
    # - Apache Tomcat
    #
    config.vm.define "server" do |node|
        node.vm.hostname = "server"    
        node.vm.network "private_network", ip: "10.11.1.101", virtualbox__intnet: true

        node.vm.provider "virtualbox" do |v| 
            v.memory = 1024 
        end 

        node.vm.network "forwarded_port", guest: 22, host: 2211, id: 'ssh', auto_correct: true
        node.ssh.forward_agent = true
 
        # provisioning con bash 
        node.vm.provision :shell, :inline => 'apt-get update'
        node.vm.provision :shell, path: "./shared/scripts/setup-java.sh"
	node.vm.provision :shell, path: "./shared/scripts/setup-db2.sh"
	node.vm.provision :shell, path: "./shared/scripts/setup-apache-tomcat.sh"
        node.vm.provision :shell, path: "./shared/scripts/startup-apache.sh", run:"always"

        node.vm.provision :shell, 
            inline: "echo  'configurazione nodo server completata'"

    end

#    #
#    # Configurazione del nodo "client", che prevede: 
#    # - Oracle Java SDK 8 
#    #
#    config.vm.define "client" do |node|
#        node.vm.hostname = "client"    
#        node.vm.network "private_network", ip: "10.11.1.201", #virtualbox__intnet: true
#
#        node.vm.provider "virtualbox" do |v| 
#            v.memory = 1024 
#        end 
#
#        node.vm.network "forwarded_port", guest: 22, host: 2221, id: 'ssh', #auto_correct: true
#        node.ssh.forward_agent = true
# 
#        # provisioning con bash 
#        node.vm.provision :shell, :inline => 'apt-get update'
#        node.vm.provision :shell, path: "./shared/scripts/setup-java.sh"
#  
#        node.vm.provision :shell, 
#            inline: "echo  'configurazione nodo client completata'"
#
#    end

end
